- hosts: all-servers
  become: yes
  vars_files:
    - hosts/{{ stage }}/group_vars/vault.yml
    - hosts/{{ stage }}/group_vars/laravel-api-sample.yml
  roles:
    - common
    - nodebrew
    - node
    - npm
    - mysql/yum-repository
    - mysql/client
    - mysql/server
    - mysql/init
    - php/base
    - php/composer
    - nginx
    - php/php-fpm
    - tls
    - jdk
    - app/laravel-api-sample
