- name: Check nodebrew Is Installed.
  become: no
  shell: bash -lc "nodebrew help"
  register: nodebrew_is_installed
  changed_when: no
  failed_when: no

- name: Download nodebrew
  become: no
  get_url:
    url: https://git.io/nodebrew
    dest: "{{ nodebrew_install_dir }}nodebrew"
  when: nodebrew_is_installed.stdout == ''

- name: Install nodebrew
  become: no
  shell: "perl {{ nodebrew_install_dir }}nodebrew setup"
  when: nodebrew_is_installed.stdout == ''

- name: Add nodebrew to PATH
  become: no
  lineinfile: >
    dest="{{ nodebrew_install_dir }}/.bash_profile"
    line="export PATH=$HOME/.nodebrew/current/bin:$PATH"
  when: nodebrew_is_installed.stdout == ''

- name: Reload .bash_profile
  become: no
  shell: source ~/.bash_profile
  when: nodebrew_is_installed.stdout == ''
