- name: Install MySQL-python for ansible mysql_user module
  yum: name=MySQL-python27 state=installed

- name: Set mysql tmp root password
  shell: cat /var/log/mysqld.log | grep password | awk '{ print $NF }' | head -n 1
  register: mysql_tmp_password

- name: Is changed mysql root password
  command: mysqlshow -uroot -p'{{ mysql_tmp_password.stdout }}'
  register: changed_root_password
  changed_when: no
  failed_when: no

- name: Set mysql root password
  command: mysql --connect-expired-password -uroot -p'{{ mysql_tmp_password.stdout }}' -e "set password for root@'localhost' = PASSWORD('{{ mysql_root_password }}')"
  when: changed_root_password.stderr.find('denied') == -1
