- name: Install php7.2
  yum : name={{item}} enablerepo=remi-php72 disablerepo=amzn-main state=present
  with_items:
    - php
    - php-devel
    - php-opcache
    - php-mbstring
    - php-pdo
    - php-mysqlnd
    - php-pecl-xdebug
    - php-fpm
    - php-xml
    - php-pecl-redis
