- name: remove ntp
  yum: name=ntp state=absent

- name: Install chrony.
  yum: name=chrony

- name: Replace chrony.conf.
  template: src=chrony.conf.j2 dest=/etc/chrony.conf owner=root group=root mode=0644

- name: Restart chrony.
  service: name=chrony state=restarted enabled=yes
  when: stage == 'local'

- name: Restart chrony.
  service: name=chronyd state=restarted enabled=yes
  when: stage in ['qa', 'dev', 'stg', 'prd']
